site_name: MqGateway
repo_name: "GitHub"
repo_url: https://github.com/aetas/mqgateway/
theme:
  name: "material"
nav:
  - Start: 'index.md'
  - User Guide:
      - 'Introduction': 'user-guide/introduction.md'
      - 'Quick Start': 'user-guide/quick-start.md'
      - 'Integration': 'user-guide/integration.md'
      - 'Naming convention': 'user-guide/naming-convention.md'
      - 'Supported devices': 'user-guide/supported-devices.md'
      - 'Installation': 'user-guide/installation.md'
      - 'Configuration': 'user-guide/configuration.md'
      - 'Logging': 'user-guide/logging.md'
      - 'Troubleshooting': 'user-guide/troubleshooting.md'
  - Hardware:
      - 'Board layout': 'hardware/board-layout.md'
      - 'Components': 'hardware/components.md'
      - 'Wiring': 'hardware/wiring.md'
      - 'I/O Expander Board': 'hardware/io-expander-board.md'
      - 'Complex devices': 'hardware/complex-devices.md'
markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - pymdownx.superfences
  - pymdownx.details